### ISSUE TITLE
http://www.abclinuxu.cz/auto/zpravicky.rss is not a valid feed.

### ISSUE THREAD

**Issue by devopsmariocom** [bearfrieze/nimbus#9]
When trying to add feed http://www.abclinuxu.cz/auto/zpravicky.rss I'm getting "is not a valid feed.", but feed appears to be valid https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.abclinuxu.cz%2Fauto%2Fzpravicky.rss

``` bash
$ curl 'http://static.liten.in/' -H 'Pragma: no-cache' -H 'Origin: http://0.0.0.0:8080' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,cs;q=0.6,es;q=0.4,pl;q=0.2,sk;q=0.2,fr;q=0.2,nl;q=0.2,it;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2438.3 Safari/537.36' -H 'Content-Type: text/plain;charset=UTF-8' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: http://0.0.0.0:8080/build/' -H 'Connection: keep-alive' -H 'X-FirePHP-Version: 0.0.6' -H 'DNT: 1' --data-binary '["http://www.abclinuxu.cz/auto/zpravicky.rss"]' --compressed
{"http://www.abclinuxu.cz/auto/zpravicky.rss":false}
```

any clue? I wasn't able to reproduce it on local server as it seems to be bit complicated to bring it to live even with Dockerfiles.

**Comment by bearfrieze** [comment]
The feed is structured in a way that is quite different from the typical RSS feed. Most RSS feeds look something like [this](http://cyber.law.harvard.edu/rss/examples/rss2sample.xml). The current implementation relies rather heavily on that being the case, and thus this is not something I can fix right away.

I might be inclined to fix this in the future if there is demand for it – so far this is the first time I have heard about the problem.

**Comment by devopsmariocom** [comment]
Yeah you are right, they use RDF instead of classic RSS, I understand that it would be some work to implement it and when there is no demand it's not worth. What I would suggest is to separate parsing into separate library, so it will be much easier for other contributors to implement it.

Anyway, thanks for your work!

**Comment by bearfrieze** [comment]
The Atom and RSS implementations are both separate packages/libraries inside the nimbus package with tests of their own. Maybe they deserve their own repos in the future if they become good (there is room for improvement). Feel free to contribute.

Thanks for your feedback, much appreciated :+1:

**Comment by devopsmariocom** [comment]
Didn't notice separate tests, I'm not go person at this moment, but I might give it a try when feedly will piss me off :wink:
